import type { Project, TechItem } from '@/types';

export const mockProjects: Project[] = [
  // BCR.CX
  {
    id: 'bcr-madeiramadeira',
    title: 'MadeiraMadeira',
    category: 'bcr',
    description:
      'Fluxo de pesquisa de satisfação via WhatsApp com validação de bugs e automações avançadas no Zendesk.',
    technologies: ['Zendesk', 'WhatsApp', 'Automações', 'CX'],
    external_url: null,
    cover_image_url: null,
    featured: true,
    status: 'published',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2024-01-01T00:00:00Z',
  },
  {
    id: 'bcr-lg',
    title: 'LG Lugar de Gente',
    category: 'bcr',
    description:
      '4 AI Agents avançados no Ultimate.ai com fluxogramas Graphviz e documentação técnica completa.',
    technologies: ['Ultimate.ai', 'AI Agents', 'Graphviz', 'Documentação'],
    external_url: null,
    cover_image_url: null,
    featured: true,
    status: 'published',
    created_at: '2024-01-02T00:00:00Z',
    updated_at: '2024-01-02T00:00:00Z',
  },
  {
    id: 'bcr-ajinomoto',
    title: 'Ajinomoto / Aminoforlife',
    category: 'bcr',
    description:
      'Pesquisa de satisfação customizada, com configuração end-to-end no Zendesk.',
    technologies: ['Zendesk', 'CX', 'Pesquisa de Satisfação'],
    external_url: null,
    cover_image_url: null,
    featured: false,
    status: 'published',
    created_at: '2024-01-03T00:00:00Z',
    updated_at: '2024-01-03T00:00:00Z',
  },
  {
    id: 'bcr-motiva',
    title: 'Motiva',
    category: 'bcr',
    description:
      'Monitoramento proativo de erros via API, com alertas operacionais em tempo real.',
    technologies: ['APIs REST', 'Monitoramento', 'Automação'],
    external_url: null,
    cover_image_url: null,
    featured: false,
    status: 'published',
    created_at: '2024-01-04T00:00:00Z',
    updated_at: '2024-01-04T00:00:00Z',
  },
  {
    id: 'bcr-ifood-pago',
    title: 'iFood Pago',
    category: 'bcr',
    description:
      'AI Agent avançado, com construção de textos institucionais e tom de voz da marca.',
    technologies: ['Ultimate.ai', 'AI Agents', 'Tom de Voz'],
    external_url: null,
    cover_image_url: null,
    featured: true,
    status: 'published',
    created_at: '2024-01-05T00:00:00Z',
    updated_at: '2024-01-05T00:00:00Z',
  },
  // Pessoais
  {
    id: 'personal-fortuny-one',
    title: 'Fortuny One',
    category: 'personal',
    description:
      'Plataforma premium de gestão financeira pessoal e familiar para o mercado brasileiro.',
    technologies: ['React', 'Firebase', 'Supabase'],
    external_url: 'https://fortunyone.com.br',
    cover_image_url: null,
    featured: true,
    status: 'published',
    created_at: '2024-02-01T00:00:00Z',
    updated_at: '2024-02-01T00:00:00Z',
  },
  {
    id: 'personal-qualityhub',
    title: 'QualityHub BCR.CX',
    category: 'personal',
    description:
      'Plataforma interna de qualidade e treinamento para toda a área de consultoria.',
    technologies: ['React', 'Vite', 'TypeScript', 'Supabase', 'Vercel'],
    external_url: null,
    cover_image_url: null,
    featured: true,
    status: 'published',
    created_at: '2024-02-02T00:00:00Z',
    updated_at: '2024-02-02T00:00:00Z',
  },
  {
    id: 'personal-fitapp',
    title: 'FitApp',
    category: 'personal',
    description:
      'App de gestão fitness multi-perfil (Aluno, Personal, Nutricionista, Admin) com módulo financeiro. Em desenvolvimento.',
    technologies: ['React', 'TypeScript', 'Supabase'],
    external_url: null,
    cover_image_url: null,
    featured: false,
    status: 'published',
    created_at: '2024-02-03T00:00:00Z',
    updated_at: '2024-02-03T00:00:00Z',
  },
  // Eventos
  {
    id: 'events-medio-grande-porte',
    title: 'Estruturação de Eventos de Médio e Grande Porte',
    category: 'events',
    description:
      'Planejamento operacional, gestão de equipes, controle financeiro, segurança e atendimento ao público em eventos de médio e grande porte.',
    technologies: ['Planejamento', 'Operações', 'Gestão de Equipes'],
    external_url: null,
    cover_image_url: null,
    featured: false,
    status: 'published',
    created_at: '2024-03-01T00:00:00Z',
    updated_at: '2024-03-01T00:00:00Z',
  },
];

export const mockTechnologies: TechItem[] = [
  { name: 'Zendesk', level: 98, category: 'cx' },
  { name: 'Supabase', level: 90, category: 'infra' },
  { name: 'Firebase', level: 80, category: 'infra' },
  { name: 'React', level: 88, category: 'dev' },
  { name: 'TypeScript', level: 85, category: 'dev' },
  { name: 'Vite', level: 85, category: 'dev' },
  { name: 'Tailwind CSS', level: 85, category: 'dev' },
  { name: 'Vercel', level: 85, category: 'infra' },
  { name: 'OpenAI', level: 85, category: 'ai' },
  { name: 'Claude / Anthropic', level: 85, category: 'ai' },
  { name: 'Ultimate.ai', level: 90, category: 'ai' },
  { name: 'Automações (Make, Zapier, n8n)', level: 85, category: 'ai' },
  { name: 'Python', level: 65, category: 'dev' },
  { name: 'APIs REST', level: 85, category: 'dev' },
  { name: 'GitHub', level: 85, category: 'dev' },
  { name: 'Figma', level: 70, category: 'design' },
];
